[[redirects]]
  from = "/"
  to = "/views/pages/login/login.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/views/pages/login/login.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/views/pages/register/register.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/views/pages/settings/settings.html"
  status = 200

[[redirects]]
  from = "/chat"
  to = "/views/pages/chat/chat.html"
  status = 200

[[redirects]]
  from = "/error_404"
  to = "/views/pages/error/error_404.html"
  status = 200

[[redirects]]
  from = "/error_500"
  to = "/views/pages/error/error_500.html"
  status = 200

[[redirects]]
  from = "/user_avatar.png"
  to = "/src/images/common/user.png"
  status = 200